### ISSUE TITLE
Static assertion fails after pulling #40

### ISSUE THREAD

**Issue by NuclearC** [tplgy/cppcodec#41]
Operating System: Windows 10 x64
Compiler: Visual C++ (VS 2017/15.6.4)

Static assert on line 266 of file access.hpp fails:

```cpp
static_assert(std::is_same<
        decltype(create_state(*(std::string*)nullptr, specific_t())),
        array_access_result_state<std::string>>::value,
        "std::string must be handled by array_access_result_state");
```

![image](https://user-images.githubusercontent.com/8341270/38077898-a65daf3e-334b-11e8-890e-18b3678b89e0.png)

**Comment by jpetso** [comment]
But it passed the AppVeyor bots! That's mean. Thanks for the report, I'll see if I can figure out what's wrong.

As a quick fix, commenting out the static assert will fix the build (but won't bring the performance benefits of #40).

**Comment by jpetso** [comment]
According to the current AppVeyor documentation [1], the build bot would have been running VS 2017/15.6.2, which passed. So they must have broken/changed something in the past two minor versions.

[1] https://www.appveyor.com/docs/build-environment/

**Comment by NuclearC** [comment]
Maybe thats my compiler broken but I doubt it. And yeah I checked appveyor build and was quite surprised that my VC++ couldnt do it.

**Comment by NuclearC** [comment]
I think it could be some kind of C++17 error, because when I switched to C++14 standard in Visual Studio I didn't get that assertion failed (I got other errors because of my project requiring C++17 stuff)

**Comment by jpetso** [comment]
I've dug out my old hard drive with Windows on it. If I can get it to boot, I might be able to do something about it. I'm definitely suspecting the compiler, MSVC has long been breaking SFINAE in surprising and annoying ways so it wouldn't be the first time. The C++ standard change is a good thought as well, are you setting any particular options?

Apart from fixing the root issue, I wonder whether I should make this a warning instead of a static assert. On the one hand, it works just fine (if a bit slower) without the special treatment; on the other hand, it's immensely useful to get reports like this one that will result in a proper fix. Thoughts?

**Comment by NuclearC** [comment]
Yeah I think just warning would be good. I think even if my project has that C++14/17 errors, if that static assertion failed, it would show but I dont see it in my output window so yeah its probably standard error.
The only thing changed in C++17 with std::string I noticed is making std::string::data() to return char* but not const char*.

**Comment by jpetso** [comment]
Oh! Of course. That would totally do it. The condition for the array access result state is that (1) it has a mutable operator[] and (2) it doesn't have a mutable data() method, because that one is already covered by the `direct_data_result_state`above. So in fact nothing is broken except that the assertion shouldn't apply in C++17 anymore because of the change to data().

Thanks for bringing that up. I'll whip up a fix (ifdef between C++ standards) tonight, and also add some post-C++11 compilers to the build bots.

**Comment by NuclearC** [comment]
Glad to hear that you found the problem :) Gonna close this issue soon
