### ISSUE TITLE
Doesn't compile with VC14

### ISSUE THREAD

**Issue by terrymah** [tplgy/cppcodec#5]
I get this error just including base64_default_rfc4648.hpp:

Error	C2535	'void cppcodec::detail::base64<CodecVariant>::pad(Result &,ResultState &,std::enable_if<,size_t>::type)': member function already defined or declared

**Comment by terrymah** [comment]
line 137 base64.hpp

**Comment by jpetso** [comment]
Thanks for the report. It seems like the `enable_if` for the `pad()` function doesn't work in VC14.

I need the `enable_if` because codec variants with `generates_padding() ==  false` might not have a `padding_symbol()` function, so calling that from `pad()` would cause an error.

I tried a few variants but getting SFINAE working on this stuff is tricky even without considering MSVC, so I don't have an easy fix at hand. I also lack a Windows/MSVC environment to test this, making it harder to fix.

I might look into possible alternatives on the weekend. Would be neat if VC14 handled this without errors.

**Comment by jpetso** [comment]
Please try the master branch from https://github.com/jpetso/cppcodec (my fork). It rephrases the existing SFINAE to match the current semantics, but Microsoft having fixed [this issue](https://connect.microsoft.com/VisualStudio/feedback/details/872124) in 2014 suggests that there's a chance it'll work.

**Comment by jpetso** [comment]
So I haven't gotten it to work, but on latest master I've rewritten the SFINAE so it uses less `enable_if<>` and that results in fewer errors. If someone can make the remaining template to work then there shouldn't be anything necessary on top of that.

**Comment by jpetso** [comment]
I believe this should be fixed in current master, since my latest commit implemented padding in a different way that doesn't use `enable_if`. Needs retesting.

**Comment by thrimbor** [comment]
Unfortunately, it still seems to be broken on VC14. I uploaded the build log [here](http://pastebin.com/gJ8zc2Ce). I tried to fix the problem myself, but my C++ wizardry isn't that good. Trying to build "base32enc" is enough to provoke the error.

The system I tried to build on was:
Windows 10 x64
Visual Studio Community 2015
Version 14.0.25424.00 Update 3
