### ISSUE TITLE
Encode from/decode to float vector does not work as expected

### ISSUE THREAD

**Issue by markstock** [tplgy/cppcodec#69]
Hi - I'm hoping to use cppcodec in a small fluid dynamics program, and the program needs to write .vtu files for ParaView (VTK uses an xml-based format, and allows base64 encoding of float arrays). I expected to be able to do the following because std::vector<float> allows `.data()` and `.size()`:
```
using base64 = cppcodec::base64_rfc4648;
std::vector<float> original({235.2158, 1.0});
std::string encoded = base64::encode(original);
```
and I assumed that it would know that each entry is 4 bytes. It doesn't. This is how to encode from a float vector:
```
std::string encoded = base64::encode((const char*)original.data(), (size_t)(sizeof(float)*original.size()));
```
This returns the encoded string `NzdrQwAAgD8=`

Now, it also seemed as if I could decode to a float vector using:
```
std::vector<float> decoded = base64::decode<std::vector<float>>(encoded);
```
but that gives me a vector of size 8 with the first entry `decoded[0]` equal to 55. Obviously it's assuming I'm decoding to `uint8_t`. How can I confirm my encoding by decoding to a `std::vector<float>` ?

**Comment by jpetso** [comment]
Let me start by saying that I didn't intend cppcodec to be a general serialization library - base64 & Co. operate on octet (i.e. byte) streams and using it with floats is entirely unanticipated. The fact that it lets you decode into a vector of floats is probably a bug.

The quick-and-dirty answer to your question:

> How can I confirm my encoding by decoding to a `std::vector<float>`?

is that you shouldn't be decoding into `std::vector<float>`. For verification of your encoded value, please decode into a memory buffer and reinterpret that as floats:

```
std::vector<uint8_t> decoded = base64::decode(encoded);
assert(decoded.size() >= sizeof(float));
float* decoded_floats = reinterpret_cast<float*>(decoded.data());
std::cout << "First value: " << decoded_floats[0];
```

// Note that the size and endianness of floats may vary by platform, so I would advise against using reinterpret_cast<> if your data needs to be transferred to another machine. Hence cppcodec not trying to support serialization in general, that opens up a whole bunch of extra scope and complexity.

I support decoding into larger-than-byte number types only because people sometimes store their characters as 16-bit wide characters, like strings in Windows. Your opened issue makes me reconsider whether this should actually be possible without explicitly opting into it, given that it can also fail like for you.

The way to decode straight into `std::vector<float>`, if that's really what's desired, would be to implement `create_state()` and its companions `init()`, `push()` & `finish()` from `data/access.hpp` with `std::vector<float>` as argument and do the opposite thing that my verification snippet did: use `std::vector<float>` as storage but expose it (via `*_result_state` wrapper) as memory buffer to be filled with a series of `char` values. Sort of like `direct_data_access_result_state`, but with modifications to account for the different size of float types.

I'm still not sure that this is a good idea - for portability considerations, I think you may be better off explicitly serializing your floats to a memory buffer (of `uint8_t` values) before base64-encoding them, and unserialize them from a decoded memory buffer.

**Comment by markstock** [comment]
Thank you for your quick and thorough reply! As I explore C++ for a second time (the first time was decades ago, pre-c++11), I am constantly amazed by the small amount of clean code required to do many operations. So when confronted with anything C-like (memcpy, playing with pointers) I get the feeling that I am doing something wrong - there should be a cleaner solution. 

As my code really only needs to export this funny floats-as-base64 data, the decoding is simply a check. But I will follow your suggestions for my tests and only use the encoding in the production code.

Thank you for creating and sharing your work, I will make sure to credit you in my project.

**Comment by jpetso** [comment]
Thanks. I wanted to point out that endianness is also a potential issue for encoding - if you encode it on an Atmel AVR32 (embedded) or OpenRISC, the same vector format floats would have a different memory layout than on an x86(-64) or ARM (when using default endianness) chip, and the resulting base64 encoding would be different too because it's sensitive to byte order.
